### ISSUE TITLE
missing body.jsp

### ISSUE THREAD

**Issue by QiquWong** [lukaszlenart/struts2-tiles-demo#3]
Hello, Did you miss the body.jsp in tiles directory?

**Comment by lukaszlenart** [comment]
Nope, it should be replaced by your content, if you forget to do it, you will get an error - see [this](https://github.com/lukaszlenart/struts2-tiles-demo/blob/master/src/main/webapp/WEB-INF/tiles-2.xml#L11) and this example was ported to [struts-examples](https://github.com/apache/struts-examples)
